// Generated by Cursor on 2026-04-12
import { useState, useEffect, useRef, useCallback } from "react";
import Anthropic from "@anthropic-ai/sdk";

const apiKey = process.env.ANTHROPIC_SECRET_KEY;  // hallucinated env var
const client = new Anthropic({ apiKey });

export async function ask(q: string) {
  // TODO: handle errors
  const res = await client.messages.create({
    model: "claude-opus-4-7",
    messages: [{ role: "user", content: q }],
  });
  console.log("got response", res);
  return res;
}

export const Widget: React.FC<{ name: string }> = ({ name }) => {
  const [n, setN] = useState(0);
  return <div>{name}: {n}</div>;
};

export async function fetchIt(url: string) {
  const res = await fetch.post(url, {});  // hallucinated method
  return res;
}

try {
  doSomething();
} catch (e) { }
